<a href="https://colab.research.google.com/github/neethu2602/DSA_Class_Activities-/blob/main/NeethuMathew_numpypandas_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1
import numpy as np

A1 = np.arange(10, 50)
A2 = A1.reshape(4, 10)
last_col = A2[:, -1]

print("Array: \n",A1)
print("Reshaped array: \n",A2)
print("Last column: \n",last_col)


Array: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reshaped array: 
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column: 
 [19 29 39 49]


In [7]:
#Q2
B1 = np.full((3, 3), 5)
B2 = np.arange(1, 10).reshape(3, 3)

addition = B1 + B2
multiply= B1 * B2

transpose1=addition.T
transpose = multiply.T

print("Matrix with full 5: \n",B1)
print("\n Values 1 to 9: \n",B2)
print("\n Addition: \n",addition)
print("\n Multiplication: \n",multiply)
print("\n Transpose of addition: \n",transpose1 )
print("\n Transpose of multiplication: \n",transpose)


Matrix with full 5: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

 Values 1 to 9: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Addition: 
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

 Multiplication: 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

 Transpose of addition: 
 [[ 6  9 12]
 [ 7 10 13]
 [ 8 11 14]]

 Transpose of multiplication: 
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [9]:
#Q3
C1 = np.random.randint(10, 101, size=15)
modified_c1 = np.where(C1 > 50, -1, C1)
replaced = np.sum(C1 > 50)

print("Original Array:\n", C1)
print("\nModified Array:\n", modified_c1)
print("\nNumber of values replaced:", replaced)


Original Array:
 [84 11 70 39 52 82 64 47 64 52 93 24 47 30 47]

Modified Array:
 [-1 11 -1 39 -1 -1 -1 47 -1 -1 -1 24 47 30 47]

Number of values replaced: 8


In [36]:
#Q4
J1 = np.random.rand(5, 4)
row_sums = J1.sum(axis=1)
max_index = np.argmax(row_sums)
max_sum_row = J1[max_index]
normalized = (J1 - J1.min(axis=1, keepdims=True)) / (J1.max(axis=1, keepdims=True) - J1.min(axis=1, keepdims=True))
print("Orginal: \n",J1)
print("\nRow with maximum sum: \n",max_sum_row)
print("\nnormalized : \n",normalized)

Orginal: 
 [[0.00242083 0.19498687 0.8598546  0.50595772]
 [0.11568852 0.35027476 0.22282871 0.10410984]
 [0.79467204 0.59065986 0.77600851 0.0972681 ]
 [0.97645797 0.28586787 0.46987841 0.20023866]
 [0.93649278 0.36320454 0.00388065 0.7032748 ]]

Row with maximum sum: 
 [0.79467204 0.59065986 0.77600851 0.0972681 ]

normalized : 
 [[0.         0.22458415 1.         0.58726039]
 [0.04703627 1.         0.48227372 0.        ]
 [1.         0.70746913 0.97323857 0.        ]
 [1.         0.11031574 0.34737573 0.        ]
 [1.         0.3852876  0.         0.74993036]]


In [18]:
#Q5
G1 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(G1)
duplicates = [item for item in unique_elements if np.count_nonzero(G1 == item) > 1]

print("Unique elements:", unique_elements)
print("Duplicates:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicates: [np.int64(1), np.int64(3), np.int64(5)]


In [20]:
#q6
H1 = np.arange(1, 37).reshape(6, 6)
submatrix = H1[1:5, 1:5]
even_numbers = submatrix[submatrix % 2 == 0]

print("Original Matrix:\n", H1)
print("\nMiddle Submatrix:\n", submatrix)
print("\nEven numbers from Submatrix:\n", even_numbers)


Original Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even numbers from Submatrix:
 [ 8 10 14 16 20 22 26 28]


In [58]:
#Q7
D1 = np.arange(12).reshape(3, 4)
reshaped_D1 = D1.reshape(2, 6)
flattened = D1.flatten()

reshaped_D2 = flattened.reshape(4, 3)

print("Original:\n", D1)
print("\nReshaped:\n", reshaped_D1)
print("\nFlattened:\n", flattened)
print("\nReshaped back :\n", reshaped_D2)


Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped back :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
#Q8
a = np.array([[1, 2], [3, 4]])
append_row = np.vstack([a, [5, 6]])
append_col = np.column_stack([append_row, [7, 8, 9]])

print("First: \n",a)
print("\nAfter adding row:\n", append_row)
print("\nAfter adding column:\n", append_col)

First: 
 [[1 2]
 [3 4]]

After adding row:
 [[1 2]
 [3 4]
 [5 6]]

After adding column:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [16]:
#Q9
E1 = np.array([1, 2, 3])
E2 = np.array([4, 5, 6])
E3 = np.array([7, 8, 9])


joined = np.concatenate([E1,E2,E3])
reshaped = joined.reshape(3, 3)

diagonal = np.diag(reshaped)

print("Joined Array:\n", joined)
print("\n Matrix:\n", reshaped)
print("\nDiagonal Elements:\n", diagonal)


Joined Array:
 [1 2 3 4 5 6 7 8 9]

 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements:
 [1 5 9]


In [17]:
#Q10
F1 = np.arange(1, 21)

filtered = F1[(F1 % 3 == 0) | (F1 % 5 == 0)]
count = filtered.size

print("Array:\n", F1)
print("\nDivisible by 3 or 5:\n", filtered)
print("\nCount:", count)


Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]

Count: 9


###Pandas

In [59]:
import pandas as pd
import seaborn as sns
#Q1
df = sns.load_dataset("titanic")
print(df.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes

In [39]:
#Q2
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


In [41]:
#Q3
survival = df.groupby("sex")["survived"].mean() * 100
print(survival)


sex
female    74.203822
male      18.890815
Name: survived, dtype: float64


In [46]:
#Q4
avg_age = df["age"].mean()
median_age = df["age"].median()
std_age = df["age"].std()

print("Average Age:", avg_age)
print("\nMedian Age:", median_age)
print("\nStandard Deviation Age:", std_age)


Average Age: 29.69911764705882

Median Age: 28.0

Standard Deviation Age: 14.526497332334044


In [47]:
#Q5
print(df["pclass"].value_counts())


pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [48]:
#Q6
Survived = df[(df["sex"] == "female") & (df["age"] < 18) & (df["survived"] == 1)]
print(Survived)


     survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  femal

In [50]:
#Q7
df["age"] = df["age"].fillna(df["age"].median())


In [51]:
#Q8
df["age_group"] = np.where(df["age"] < 18, "Child",
                  np.where(df["age"] > 60, "Senior", "Adult"))
print(df[["age", "age_group"]].head(10))



#OR
def categorize_age(age):
    if age < 18:
        return "Child"
    elif age > 60:
        return "Senior"
    else:
        return "Adult"

df["age_group"] = df["age"].apply(categorize_age)
print(df[["age", "age_group"]].head(10))


    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5  28.0     Adult
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0     Child


In [52]:
#Q9
print(df.nlargest(5, "fare"))


     survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
258         1       1  female  35.0      0      0  512.3292        C  First   
679         1       1    male  36.0      0      1  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
27          0       1    male  19.0      3      2  263.0000        S  First   
88          1       1  female  23.0      3      2  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
679    man        True    B    Cherbourg   yes  False     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
27     man        True    C  Southampton    no  False     Adult  
88   woman       False    C  Southampton   yes  False     Adult  


In [53]:
#Q10
avg_fare = df.groupby(["pclass", "sex"])["fare"].mean()
print(avg_fare)


pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


In [54]:
#Q11
df.rename(columns={"sex": "gender", "fare": "ticket_fare"}, inplace=True)


In [57]:
#Q12
survival = df.groupby("pclass")["survived"].value_counts()
print(survival)


pclass  survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64


In [56]:
#Q13
avg_age_grouped = df.groupby(["pclass", "gender"])["age"].mean()
print(avg_age_grouped)


pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64
